### ISSUE TITLE
Example dashtable can't recognize bs4

### ISSUE THREAD

**Issue by qwbjtu2015** [dockerizeme/dockerizeme#2]
Hello.
I downloaded and tested DockerizeMe according to the README document. First, I started the neo4j container, and then I used command `npm run dockerizeme --verbose examples/dashtable/snippet.py> Dockerfile` and got the following result:

> dockerizeme@1.0.0 dockerizeme /root/dockerizeme
node src/bin.js "examples/dashtable/snippet.py"
FROM python:2.7.13
COPY examples/dashtable/snippet.py /snippet.py
RUN ["pip","install","dashtable"]
CMD ["python","/snippet.py"]

The package dashtable depends on bs4. Why isn't it recognized here? Is the dynamic analysis feature temporarily unimplemented or am I using it incorrectly? 
Thanks~

**Comment by dockerizeme** [comment]
If you run

```
npm run dockerizeme -- --verbose examples/dashtable/snippet.py
```

and see the following log entry

```
Could not perform a reverse package lookup for resource: dashtable
```

this likely indicates an issue communicating with the Neo4j database. When this happens, DockerizeMe will progress without dependency information provided by the database and report only `dashtable` as a dependency.

The easiest way to guarantee you have everything set up correctly is to use the VM image from our [ICSE 2019 artifact](https://github.com/dockerizeme/dockerizeme/releases/tag/ICSE2019-ArtifactEvaluation). The login username and password are both `vagrant`. All project source code is in the `/vagrant` directory. The executable `dockerizeme` is already on the PATH, and all required services will start at boot.

You should also look at [V2](https://github.com/v2-project/v2), an improved version of DockerizeMe that handles versions.

**Comment by qwbjtu2015** [comment]
Thank you very much for your reply.

I found the problem. After I started the neo4j database, I forgot to import the data `neo4j/neo4j.dump`. After the import, the parsing results are correct. In addition, I also downloaded the VM image, which is really convenient. Thanks again~
